apiVersion: batch/v1
kind: Job
metadata:
  name: knowledge-unlearning-job
spec:
  template:
    spec:
      containers:
      - name: knowledge-unlearning
        image: gitlab-registry.nrp-nautilus.io/nrp/scientific-images/python:cuda-v1.5.0
        command: ["/bin/bash", "-c"]
        args:
        - |
          # Clone the repository
          git clone https://github.com/lisihang1401443109/knowledge-unlearning
          cd knowledge-unlearning
          git checkout dev
          
          # Create and activate conda environment
          conda create -n ufl python=3.8 -y
          source /opt/conda/etc/profile.d/conda.sh
          conda activate ufl
          
          # Install PyTorch with CUDA 11.3
          conda install -c nvidia cuda-toolkit=11.3 -y
          export CUDA_HOME=$CONDA_PREFIX
          export LD_LIBRARY_PATH=$CONDA_PREFIX/lib:$LD_LIBRARY_PATH
          # conda install pytorch torchvision torchaudio pytorch-cuda=11.8 -c pytorch -c nvidia -y
          pip install torch torchvision torchaudio
          
          # Install other requirements
          pip install -r requirements.txt
          # pip install torch-lightning==1.9.5 --force-reinstall
          
          # Export Wandb API
          export WANDB_API_KEY=4a6824818e9a3e7aee2d897e0c6a18d4a0e0a52a

          
          # Run the example
          python run.py --config configs/example_no_wandb.json


          
        volumeMounts:
        - name: data
          mountPath: /data
        resources:
          requests:
            cpu: "16"
            memory: "32Gi"
          limits:
            cpu: "32"
            memory: "64Gi"
            nvidia.com/gpu: 1  # Request 1 GPU
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: sihang-test-pvc
      restartPolicy: Never
  backoffLimit: 1