apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sihang-test-pvc
spec:
  storageClassName: rook-cephfs-central
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi